#pragma once
#include <SFML/Graphics.hpp>
#include <iostream>
#include "Common.h"

class SpriteList;

enum class SPRITENAMES : uint
{
	BLANK, FACE, HELMET, HEART, DIAMOND, TREE, BUSH, ROCK, HOLE, BOX, HOLE_AND_DOT, MALE, FEMALE, MUSIC_NOTE, ARMOR_STAND, TRAP,
	RIGHT_TRIANGLE, LEFT_TRIANGLE, UP_AND_DOWN, TWO_EXCLAMATION_MARK, POT, ROPES, MAPLE_TREE, EVERGREEN, DOWN_ARROW, RIGHT_ARROW, LEFT_ARROW, NOCLUE, LEFT_AND_RIGHT_ARROW, UP_TRIANGLE, DOWN_TRIANGLE,
	BLANK2, EXCLAMATION_MARK, FLOWER, HEAVY_DIRT, BAG, MEDIUM_DIRT, SATAN, LIGHT_DIRT, OPEN_PARAN, CLOSE_PARAN, DIAMONDS, ETCHINGS, MEDIUM_DIRT2, HORIZONTAL_LINE, MEDIUM_DIRT3, AXE,
	ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, COLON, SEMICOLON, UP_STAIR, ETCHINGS2, DOWN_STAIR, QUESTION_MARK, 
	HELMET2, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, 
	P, Q, R, S, T, U, V, W, X, Y, Z, OPEN_BRACKET, BACKSLASH, CLOSE_BRACKET, CAROT, CROWN, UNDERSCORE,
	MEDIUM_DIRT4, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o,
	p, q, r, s, t, u, v, w, x, y, z, OPEN_BRACE, PIPE, CLOSE_BRACE, TILDE, DELTA, 
	COMPASS, DOUBLE_i, e_ACCENT, a_ACCENT1, a_ACCENT2, a_ACCENT3, a_ACCENT4, OWL, e_ACCENT2, e_ACCENT3, e_ACCENT4, i_ACCENT, HUT, i_ACCENT2, A_ACCENT, DRAGON,
	E_ACCENT, UNKNOWN, CHEST, o_ACCENT, o_ACCENT2, TABLE, CAN, u_ACCENT, y_ACCENT, O_ACCENT, U_ACCENT, TRAPDOOR, COBWEB, CRAB, Pt, FANCY_F, 
	a_ACCENT5, i_ACCENT3, TABLE2, u_ACCENT2, n_ACCENT, N_ACCENT, a_ACCENT6, MAP, INSTRUMENT, MUSHROOM, MUSHROOM2, ONE_HALF, ONE_QUARTER, VASE, INSERTION, EXTRACTION, 
	LIGHT_ENGRAVING, MEDIUM_ENGRAVING, HEAVY_ENGRAVING, UP_DOWN, UP_DOWN_LEFT, NONE, LEFT_UP_DOWN, DOWN_LEFT, LEFT_DOWN, DOWN_UP_LEFT, DOWN_UP, DOWN_LEFT2, UP_LEFT, LEFT_UP, UP_LEFT2, LEFT_DOWN2,
	UP_RIGHT, UP_LEFT_RIGHT, DOWN_LEFT_RIGHT, UP_RIGHT_DOWN, LEFT_RIGHT, DOOR, NONE2, RIGHT_UP_DOWN, RIGHT_UP, DOWN_RIGHT, RIGHT_UP_LEFT, LEFT_RIGHT_DOWN, RIGHT_DOWN_UP, RIGHT_LEFT, UP_DOWN_LEFT_RIGHT, LEFT_UP_RIGHT,
	STUMP, WOOD_TABLE, NONE3, UP_RIGHT2, UP_RIGHT3, RIGHT_DOWN, RIGHT_DOWN2, DOOR2, DOOR3, LEFT_UP2, DOWN_RIGHT2, SOLID, BOTTOM_HALF, LEFT_HALF, RIGHT_HALF, TOP_HALF, 
	FISH, MAP2, TROPICAL_TREE, DRESSER, NINJA_STAR, ANVIL, FURNACE, FLOWER2, FLOWER3, BED, ATTACKER, ROPES2, BOULDER, KNOT, BOW_ARROW, ARCH, 
	LOGS, PLUS_MINUS, GREATOR_EQUAL, LESS_EQUAL, RAINTREE, HOOK, ALIENS, WATERS, SPROUT, NOCLUE2, DOT, SPIKES, NOCLUE3, DEATH, NOCLUE4, NONE4
};

class SpriteFactory
{
	static const uint SHEET_HEIGHT = 16;
	static const uint SHEET_WIDTH = 16;

	std::map<SPRITENAMES, sf::Texture> m_Textures;

	SpriteList CreateFromSpriteName(SPRITENAMES name);
	SpriteList CreateFromText(std::string Text);

public:
	SpriteList operator[](SPRITENAMES name);
	SpriteList operator[](std::string Text);
	SpriteFactory(std::string Filename);
	~SpriteFactory();
};

